services:
  
  # Oracle service (label used to access the service container)
  oracle:
    
    # Docker Hub image (feel free to change the tag "latest" to any other available one)
    image: gvenzl/oracle-xe:18.4.0-slim-faststart
    shm_size: '2gb'
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 2G
    
    # Provide passwords and other environment variables to container
    environment:
      ORACLE_PASSWORD: syspassword
#      ORACLE_DATABASE: MYDB
#      APP_USER: appuser
#      APP_USER_PASSWORD: apppassword
    
    # Provide startup script
    volumes:
      - ./initialDb:/container-entrypoint-startdb.d
        
      # Forward Oracle port
    ports:
      - 1521:1521
    
    # Provide healthcheck script options for startup
#    options: >-
#      --health-cmd healthcheck.sh
#      --health-interval 10s
#      --health-timeout 5s
#      --health-retries 10